/**
 * 周报系统 - 模拟数据
 * 注意：此文件不导入类型，使用时再进行类型断言
 */

// 当前用户 - 可根据测试需要切换角色: 'admin' | 'leader' | 'member'
export const currentUser = {
  id: 'user-001',
  name: '张经理',
  avatar: '',
  role: 'admin', // 可切换为 'leader' 或 'member' 测试不同角色视图
  department: '管理层',
  email: 'zhang@company.com',
  groupId: null, // admin 没有所属组
};

// 部门列表
export const departmentList = [
  { id: 'dept-001', name: '综合开发部' },
  { id: 'dept-002', name: '财富开发部' },
  { id: 'dept-003', name: '数智平台部' },
  { id: 'dept-004', name: '系统运行部' },
];

// 大组列表（Leader 对应大组长）
export const groupList = [
  // 综合开发部
  {
    id: 'group-001',
    name: '策略终端组',
    leaderId: 'user-002',
    leaderName: '李明',
    department: '综合开发部',
    description: '负责策略终端相关产品研发',
    createdAt: '2023-01-01',
  },
  {
    id: 'group-002',
    name: '投资组',
    leaderId: 'user-003',
    leaderName: '王强',
    department: '综合开发部',
    description: '负责投资相关业务',
    createdAt: '2023-01-01',
  },
  {
    id: 'group-003',
    name: '综运组',
    leaderId: 'user-004',
    leaderName: '赵军',
    department: '综合开发部',
    description: '负责综合运营业务',
    createdAt: '2023-01-01',
  },
  // 财富开发部
  {
    id: 'group-004',
    name: '产品组',
    leaderId: 'user-005',
    leaderName: '刘芳',
    department: '财富开发部',
    description: '负责产品规划和设计',
    createdAt: '2023-01-01',
  },
  {
    id: 'group-005',
    name: '渠道组',
    leaderId: 'user-006',
    leaderName: '陈华',
    department: '财富开发部',
    description: '负责渠道开发和维护',
    createdAt: '2023-01-01',
  },
  {
    id: 'group-006',
    name: '营销组',
    leaderId: 'user-007',
    leaderName: '周丽',
    department: '财富开发部',
    description: '负责营销推广',
    createdAt: '2023-01-01',
  },
  {
    id: 'group-007',
    name: '运营组',
    leaderId: 'user-008',
    leaderName: '吴刚',
    department: '财富开发部',
    description: '负责日常运营管理',
    createdAt: '2023-01-01',
  },
  // 数智平台部
  {
    id: 'group-008',
    name: 'AI组',
    leaderId: 'user-009',
    leaderName: '郑智',
    department: '数智平台部',
    description: '负责人工智能技术研发',
    createdAt: '2023-01-01',
  },
  {
    id: 'group-009',
    name: '管理组',
    leaderId: 'user-010',
    leaderName: '孙敏',
    department: '数智平台部',
    description: '负责平台管理工作',
    createdAt: '2023-01-01',
  },
  {
    id: 'group-010',
    name: '规划组',
    leaderId: 'user-011',
    leaderName: '杨帆',
    department: '数智平台部',
    description: '负责技术规划',
    createdAt: '2023-01-01',
  },
  {
    id: 'group-011',
    name: '交易组',
    leaderId: 'user-012',
    leaderName: '黄磊',
    department: '数智平台部',
    description: '负责交易系统开发',
    createdAt: '2023-01-01',
  },
  {
    id: 'group-012',
    name: '平台组',
    leaderId: 'user-013',
    leaderName: '林峰',
    department: '数智平台部',
    description: '负责平台架构',
    createdAt: '2023-01-01',
  },
  {
    id: 'group-013',
    name: '数据组',
    leaderId: 'user-014',
    leaderName: '徐静',
    department: '数智平台部',
    description: '负责数据治理',
    createdAt: '2023-01-01',
  },
  // 系统运行部
  {
    id: 'group-014',
    name: '安全组',
    leaderId: 'user-015',
    leaderName: '谢安',
    department: '系统运行部',
    description: '负责信息安全',
    createdAt: '2023-01-01',
  },
  {
    id: 'group-015',
    name: '设施组',
    leaderId: 'user-016',
    leaderName: '罗维',
    department: '系统运行部',
    description: '负责基础设施',
    createdAt: '2023-01-01',
  },
  {
    id: 'group-016',
    name: '运维组',
    leaderId: 'user-017',
    leaderName: '马腾',
    department: '系统运行部',
    description: '负责系统运维',
    createdAt: '2023-01-01',
  },
];

// 小组成员配置（小组名称 → 对应大组）
export const smallGroupMapping = {
  // 策略终端组
  '策略终端组': { groupId: 'group-001', department: '综合开发部' },
  '策略终端组-量化组': { groupId: 'group-001', department: '综合开发部' },
  '策略终端组-专业终端组': { groupId: 'group-001', department: '综合开发部' },
  // 投资组
  '投资组': { groupId: 'group-002', department: '综合开发部' },
  // 综运组
  '综运组': { groupId: 'group-003', department: '综合开发部' },
  '综运组-开发组': { groupId: 'group-003', department: '综合开发部' },
  '综运组-内控组': { groupId: 'group-003', department: '综合开发部' },
  '综运组-数字组': { groupId: 'group-003', department: '综合开发部' },
  '综运组-业务组': { groupId: 'group-003', department: '综合开发部' },
  // 产品组
  '产品组': { groupId: 'group-004', department: '财富开发部' },
  // 渠道组
  '渠道组-渠道二组（员工端）': { groupId: 'group-005', department: '财富开发部' },
  '渠道组-渠道一组（客户端）': { groupId: 'group-005', department: '财富开发部' },
  // 营销组
  '营销组': { groupId: 'group-006', department: '财富开发部' },
  // 运营组
  '运营组': { groupId: 'group-007', department: '财富开发部' },
  // AI组
  'AI组': { groupId: 'group-008', department: '数智平台部' },
  // 管理组
  '管理组': { groupId: 'group-009', department: '数智平台部' },
  // 规划组
  '规划组': { groupId: 'group-010', department: '数智平台部' },
  // 交易组
  '交易组': { groupId: 'group-011', department: '数智平台部' },
  '交易组-集中交易组': { groupId: 'group-011', department: '数智平台部' },
  '交易组-通用终端组': { groupId: 'group-011', department: '数智平台部' },
  // 平台组
  '平台组': { groupId: 'group-012', department: '数智平台部' },
  // 数据组
  '数据组': { groupId: 'group-013', department: '数智平台部' },
  // 安全组
  '安全组': { groupId: 'group-014', department: '系统运行部' },
  // 设施组
  '设施组': { groupId: 'group-015', department: '系统运行部' },
  '设施组-基础软件组': { groupId: 'group-015', department: '系统运行部' },
  '设施组-技术支持组': { groupId: 'group-015', department: '系统运行部' },
  '设施组-网络组': { groupId: 'group-015', department: '系统运行部' },
  // 运维组
  '运维组': { groupId: 'group-016', department: '系统运行部' },
  '运维组-测试组': { groupId: 'group-016', department: '系统运行部' },
  '运维组-数智组': { groupId: 'group-016', department: '系统运行部' },
  '运维组-运行组': { groupId: 'group-016', department: '系统运行部' },
  '运维组-运维二组': { groupId: 'group-016', department: '系统运行部' },
  '运维组-运维一组': { groupId: 'group-016', department: '系统运行部' },
};

// 团队成员列表
export const teamMembers = [
  // Admin
  {
    id: 'user-001',
    name: '张经理',
    department: '管理层',
    smallGroup: '',
    role: 'admin',
    email: 'zhang@company.com',
    joinDate: '2020-01-15',
    isActive: true,
    groupId: null,
  },
  // 策略终端组 - 大组长: 李明
  {
    id: 'user-002',
    name: '李明',
    department: '综合开发部',
    smallGroup: '策略终端组',
    role: 'leader',
    email: 'liming@company.com',
    joinDate: '2019-03-20',
    isActive: true,
    groupId: 'group-001',
  },
  {
    id: 'user-101',
    name: '张伟',
    department: '综合开发部',
    smallGroup: '策略终端组-量化组',
    role: 'member',
    email: 'zhangwei@company.com',
    joinDate: '2021-06-10',
    isActive: true,
    groupId: 'group-001',
  },
  {
    id: 'user-102',
    name: '王磊',
    department: '综合开发部',
    smallGroup: '策略终端组-专业终端组',
    role: 'member',
    email: 'wanglei@company.com',
    joinDate: '2022-02-15',
    isActive: true,
    groupId: 'group-001',
  },
  // 投资组 - 大组长: 王强
  {
    id: 'user-003',
    name: '王强',
    department: '综合开发部',
    smallGroup: '投资组',
    role: 'leader',
    email: 'wangqiang@company.com',
    joinDate: '2018-08-20',
    isActive: true,
    groupId: 'group-002',
  },
  {
    id: 'user-201',
    name: '刘洋',
    department: '综合开发部',
    smallGroup: '投资组',
    role: 'member',
    email: 'liuyang@company.com',
    joinDate: '2021-09-01',
    isActive: true,
    groupId: 'group-002',
  },
  // 综运组 - 大组长: 赵军
  {
    id: 'user-004',
    name: '赵军',
    department: '综合开发部',
    smallGroup: '综运组',
    role: 'leader',
    email: 'zhaojun@company.com',
    joinDate: '2019-05-10',
    isActive: true,
    groupId: 'group-003',
  },
  {
    id: 'user-301',
    name: '孙涛',
    department: '综合开发部',
    smallGroup: '综运组-开发组',
    role: 'member',
    email: 'suntao@company.com',
    joinDate: '2022-03-15',
    isActive: true,
    groupId: 'group-003',
  },
  {
    id: 'user-302',
    name: '周杰',
    department: '综合开发部',
    smallGroup: '综运组-内控组',
    role: 'member',
    email: 'zhoujie@company.com',
    joinDate: '2021-11-20',
    isActive: true,
    groupId: 'group-003',
  },
  {
    id: 'user-303',
    name: '吴倩',
    department: '综合开发部',
    smallGroup: '综运组-数字组',
    role: 'member',
    email: 'wuqian@company.com',
    joinDate: '2023-01-08',
    isActive: true,
    groupId: 'group-003',
  },
  // 产品组 - 大组长: 刘芳
  {
    id: 'user-005',
    name: '刘芳',
    department: '财富开发部',
    smallGroup: '产品组',
    role: 'leader',
    email: 'liufang@company.com',
    joinDate: '2019-07-15',
    isActive: true,
    groupId: 'group-004',
  },
  {
    id: 'user-401',
    name: '陈静',
    department: '财富开发部',
    smallGroup: '产品组',
    role: 'member',
    email: 'chenjing@company.com',
    joinDate: '2022-06-20',
    isActive: true,
    groupId: 'group-004',
  },
  // 渠道组 - 大组长: 陈华
  {
    id: 'user-006',
    name: '陈华',
    department: '财富开发部',
    smallGroup: '渠道组',
    role: 'leader',
    email: 'chenhua@company.com',
    joinDate: '2018-12-01',
    isActive: true,
    groupId: 'group-005',
  },
  {
    id: 'user-501',
    name: '杨超',
    department: '财富开发部',
    smallGroup: '渠道组-渠道一组（客户端）',
    role: 'member',
    email: 'yangchao@company.com',
    joinDate: '2021-04-10',
    isActive: true,
    groupId: 'group-005',
  },
  {
    id: 'user-502',
    name: '朱琳',
    department: '财富开发部',
    smallGroup: '渠道组-渠道二组（员工端）',
    role: 'member',
    email: 'zhulin@company.com',
    joinDate: '2022-08-15',
    isActive: true,
    groupId: 'group-005',
  },
  // 营销组 - 大组长: 周丽
  {
    id: 'user-007',
    name: '周丽',
    department: '财富开发部',
    smallGroup: '营销组',
    role: 'leader',
    email: 'zhouli@company.com',
    joinDate: '2019-09-20',
    isActive: true,
    groupId: 'group-006',
  },
  {
    id: 'user-601',
    name: '黄磊',
    department: '财富开发部',
    smallGroup: '营销组',
    role: 'member',
    email: 'huanglei@company.com',
    joinDate: '2022-01-10',
    isActive: true,
    groupId: 'group-006',
  },
  // 运营组 - 大组长: 吴刚
  {
    id: 'user-008',
    name: '吴刚',
    department: '财富开发部',
    smallGroup: '运营组',
    role: 'leader',
    email: 'wugang@company.com',
    joinDate: '2018-06-15',
    isActive: true,
    groupId: 'group-007',
  },
  {
    id: 'user-701',
    name: '许娜',
    department: '财富开发部',
    smallGroup: '运营组',
    role: 'member',
    email: 'xuna@company.com',
    joinDate: '2021-12-01',
    isActive: true,
    groupId: 'group-007',
  },
  // AI组 - 大组长: 郑智
  {
    id: 'user-009',
    name: '郑智',
    department: '数智平台部',
    smallGroup: 'AI组',
    role: 'leader',
    email: 'zhengzhi@company.com',
    joinDate: '2019-04-01',
    isActive: true,
    groupId: 'group-008',
  },
  {
    id: 'user-801',
    name: '林峰',
    department: '数智平台部',
    smallGroup: 'AI组',
    role: 'member',
    email: 'linfeng@company.com',
    joinDate: '2022-05-20',
    isActive: true,
    groupId: 'group-008',
  },
  // 管理组 - 大组长: 孙敏
  {
    id: 'user-010',
    name: '孙敏',
    department: '数智平台部',
    smallGroup: '管理组',
    role: 'leader',
    email: 'sunmin@company.com',
    joinDate: '2018-11-10',
    isActive: true,
    groupId: 'group-009',
  },
  // 规划组 - 大组长: 杨帆
  {
    id: 'user-011',
    name: '杨帆',
    department: '数智平台部',
    smallGroup: '规划组',
    role: 'leader',
    email: 'yangfan@company.com',
    joinDate: '2019-02-20',
    isActive: true,
    groupId: 'group-010',
  },
  // 交易组 - 大组长: 黄磊(重名，用ID区分)
  {
    id: 'user-012',
    name: '黄磊',
    department: '数智平台部',
    smallGroup: '交易组',
    role: 'leader',
    email: 'huanglei2@company.com',
    joinDate: '2018-09-15',
    isActive: true,
    groupId: 'group-011',
  },
  {
    id: 'user-1101',
    name: '高翔',
    department: '数智平台部',
    smallGroup: '交易组-集中交易组',
    role: 'member',
    email: 'gaoxiang@company.com',
    joinDate: '2021-07-10',
    isActive: true,
    groupId: 'group-011',
  },
  {
    id: 'user-1102',
    name: '梁雨',
    department: '数智平台部',
    smallGroup: '交易组-通用终端组',
    role: 'member',
    email: 'liangyu@company.com',
    joinDate: '2022-09-01',
    isActive: true,
    groupId: 'group-011',
  },
  // 平台组 - 大组长: 林峰(重名，用ID区分)
  {
    id: 'user-013',
    name: '林峰',
    department: '数智平台部',
    smallGroup: '平台组',
    role: 'leader',
    email: 'linfeng2@company.com',
    joinDate: '2019-01-20',
    isActive: true,
    groupId: 'group-012',
  },
  // 数据组 - 大组长: 徐静
  {
    id: 'user-014',
    name: '徐静',
    department: '数智平台部',
    smallGroup: '数据组',
    role: 'leader',
    email: 'xujing@company.com',
    joinDate: '2018-07-01',
    isActive: true,
    groupId: 'group-013',
  },
  {
    id: 'user-1301',
    name: '宋佳',
    department: '数智平台部',
    smallGroup: '数据组',
    role: 'member',
    email: 'songjia@company.com',
    joinDate: '2022-04-15',
    isActive: true,
    groupId: 'group-013',
  },
  // 安全组 - 大组长: 谢安
  {
    id: 'user-015',
    name: '谢安',
    department: '系统运行部',
    smallGroup: '安全组',
    role: 'leader',
    email: 'xiean@company.com',
    joinDate: '2019-06-10',
    isActive: true,
    groupId: 'group-014',
  },
  {
    id: 'user-1401',
    name: '韩冰',
    department: '系统运行部',
    smallGroup: '安全组',
    role: 'member',
    email: 'hanbing@company.com',
    joinDate: '2021-08-20',
    isActive: true,
    groupId: 'group-014',
  },
  // 设施组 - 大组长: 罗维
  {
    id: 'user-016',
    name: '罗维',
    department: '系统运行部',
    smallGroup: '设施组',
    role: 'leader',
    email: 'luowei@company.com',
    joinDate: '2018-10-15',
    isActive: true,
    groupId: 'group-015',
  },
  {
    id: 'user-1501',
    name: '唐凯',
    department: '系统运行部',
    smallGroup: '设施组-基础软件组',
    role: 'member',
    email: 'tangkai@company.com',
    joinDate: '2022-02-10',
    isActive: true,
    groupId: 'group-015',
  },
  {
    id: 'user-1502',
    name: '曹颖',
    department: '系统运行部',
    smallGroup: '设施组-技术支持组',
    role: 'member',
    email: 'caoying@company.com',
    joinDate: '2021-05-15',
    isActive: true,
    groupId: 'group-015',
  },
  {
    id: 'user-1503',
    name: '彭飞',
    department: '系统运行部',
    smallGroup: '设施组-网络组',
    role: 'member',
    email: 'pengfei@company.com',
    joinDate: '2023-03-01',
    isActive: true,
    groupId: 'group-015',
  },
  // 运维组 - 大组长: 马腾
  {
    id: 'user-017',
    name: '马腾',
    department: '系统运行部',
    smallGroup: '运维组',
    role: 'leader',
    email: 'mateng@company.com',
    joinDate: '2018-08-01',
    isActive: true,
    groupId: 'group-016',
  },
  {
    id: 'user-1601',
    name: '邓强',
    department: '系统运行部',
    smallGroup: '运维组-测试组',
    role: 'member',
    email: 'dengqiang@company.com',
    joinDate: '2021-10-20',
    isActive: true,
    groupId: 'group-016',
  },
  {
    id: 'user-1602',
    name: '曾丽',
    department: '系统运行部',
    smallGroup: '运维组-数智组',
    role: 'member',
    email: 'zengli@company.com',
    joinDate: '2022-07-15',
    isActive: true,
    groupId: 'group-016',
  },
  {
    id: 'user-1603',
    name: '董浩',
    department: '系统运行部',
    smallGroup: '运维组-运行组',
    role: 'member',
    email: 'donghao@company.com',
    joinDate: '2021-03-10',
    isActive: true,
    groupId: 'group-016',
  },
  {
    id: 'user-1604',
    name: '袁雪',
    department: '系统运行部',
    smallGroup: '运维组-运维一组',
    role: 'member',
    email: 'yuanxue@company.com',
    joinDate: '2022-11-01',
    isActive: true,
    groupId: 'group-016',
  },
  {
    id: 'user-1605',
    name: '蒋文',
    department: '系统运行部',
    smallGroup: '运维组-运维二组',
    role: 'member',
    email: 'jiangwen@company.com',
    joinDate: '2023-01-15',
    isActive: true,
    groupId: 'group-016',
  },
];

// 组成员关系（基于大组）
export const groupMembers = teamMembers
  .filter((m) => m.groupId !== null)
  .map((m) => ({
    groupId: m.groupId,
    userId: m.id,
    userName: m.name,
    joinedAt: m.joinDate,
  }));

// 任务列表
export const taskList = [
  {
    id: 'task-001',
    title: '完成量化策略回测模块开发',
    description: '实现策略回测引擎，支持多因子模型回测',
    assigneeId: 'user-101',
    assigneeName: '张伟',
    status: 'completed',
    priority: 'high',
    deadline: '2026-05-20',
    progress: 100,
    createdAt: '2026-05-10',
    updatedAt: '2026-05-19',
    relatedReportIds: ['report-001'],
  },
  {
    id: 'task-002',
    title: '设计专业终端UI界面',
    description: '完成专业终端视觉设计，包含图表组件',
    assigneeId: 'user-102',
    assigneeName: '王磊',
    status: 'in_progress',
    priority: 'medium',
    deadline: '2026-05-28',
    progress: 65,
    createdAt: '2026-05-15',
    updatedAt: '2026-05-25',
    relatedReportIds: [],
  },
  {
    id: 'task-003',
    title: '投资组合风险监控系统',
    description: '开发实时风险监控和预警功能',
    assigneeId: 'user-201',
    assigneeName: '刘洋',
    status: 'overdue',
    priority: 'high',
    deadline: '2026-05-22',
    progress: 30,
    createdAt: '2026-05-12',
    updatedAt: '2026-05-23',
    relatedReportIds: [],
  },
  {
    id: 'task-004',
    title: '综运数字平台数据看板',
    description: '开发运营管理数据可视化看板',
    assigneeId: 'user-303',
    assigneeName: '吴倩',
    status: 'todo',
    priority: 'medium',
    deadline: '2026-05-27',
    progress: 0,
    createdAt: '2026-05-24',
    updatedAt: '2026-05-24',
    relatedReportIds: [],
  },
  {
    id: 'task-005',
    title: '财富APP客户端功能迭代',
    description: '实现新的理财产品展示页面',
    assigneeId: 'user-501',
    assigneeName: '杨超',
    status: 'in_progress',
    priority: 'high',
    deadline: '2026-06-05',
    progress: 45,
    createdAt: '2026-05-18',
    updatedAt: '2026-05-24',
    relatedReportIds: ['report-002'],
  },
  {
    id: 'task-006',
    title: 'AI智能客服模型训练',
    description: '基于历史数据训练客服对话模型',
    assigneeId: 'user-801',
    assigneeName: '林峰',
    status: 'completed',
    priority: 'medium',
    deadline: '2026-05-18',
    progress: 100,
    createdAt: '2026-05-08',
    updatedAt: '2026-05-17',
    relatedReportIds: ['report-003'],
  },
  {
    id: 'task-007',
    title: '交易系统性能优化',
    description: '优化撮合引擎性能，提升吞吐量',
    assigneeId: 'user-1101',
    assigneeName: '高翔',
    status: 'overdue',
    priority: 'high',
    deadline: '2026-05-25',
    progress: 70,
    createdAt: '2026-05-05',
    updatedAt: '2026-05-26',
    relatedReportIds: ['report-004'],
  },
  {
    id: 'task-008',
    title: '数据仓库ETL流程优化',
    description: '优化数据抽取转换流程，缩短处理时间',
    assigneeId: 'user-1301',
    assigneeName: '宋佳',
    status: 'in_progress',
    priority: 'medium',
    deadline: '2026-06-10',
    progress: 50,
    createdAt: '2026-05-15',
    updatedAt: '2026-05-24',
    relatedReportIds: [],
  },
  {
    id: 'task-009',
    title: '安全漏洞扫描和修复',
    description: '完成季度安全扫描，修复高危漏洞',
    assigneeId: 'user-1401',
    assigneeName: '韩冰',
    status: 'todo',
    priority: 'high',
    deadline: '2026-06-01',
    progress: 10,
    createdAt: '2026-05-20',
    updatedAt: '2026-05-24',
    relatedReportIds: [],
  },
  {
    id: 'task-010',
    title: '服务器扩容和迁移',
    description: '完成新服务器上架和旧设备迁移',
    assigneeId: 'user-1501',
    assigneeName: '唐凯',
    status: 'completed',
    priority: 'high',
    deadline: '2026-05-20',
    progress: 100,
    createdAt: '2026-05-05',
    updatedAt: '2026-05-19',
    relatedReportIds: [],
  },
  {
    id: 'task-011',
    title: '自动化测试平台搭建',
    description: '搭建CI/CD自动化测试流水线',
    assigneeId: 'user-1601',
    assigneeName: '邓强',
    status: 'in_progress',
    priority: 'medium',
    deadline: '2026-06-15',
    progress: 35,
    createdAt: '2026-05-12',
    updatedAt: '2026-05-24',
    relatedReportIds: [],
  },
  {
    id: 'task-012',
    title: '营销数据分析报表',
    description: '开发营销活动效果分析报表',
    assigneeId: 'user-601',
    assigneeName: '黄磊',
    status: 'draft',
    priority: 'low',
    deadline: '2026-06-20',
    progress: 0,
    createdAt: '2026-05-25',
    updatedAt: '2026-05-25',
    relatedReportIds: [],
  },
];

// 任务历史记录
export const taskHistoryList = [
  {
    id: 'hist-001',
    taskId: 'task-001',
    action: '创建任务',
    operatorId: 'user-002',
    operatorName: '李明',
    createdAt: '2026-05-10T09:00:00',
  },
  {
    id: 'hist-002',
    taskId: 'task-001',
    action: '状态变更',
    oldValue: 'todo',
    newValue: 'in_progress',
    operatorId: 'user-101',
    operatorName: '张伟',
    createdAt: '2026-05-11T10:30:00',
  },
  {
    id: 'hist-003',
    taskId: 'task-001',
    action: '进度更新',
    oldValue: '0%',
    newValue: '50%',
    operatorId: 'user-101',
    operatorName: '张伟',
    createdAt: '2026-05-15T16:00:00',
  },
  {
    id: 'hist-004',
    taskId: 'task-001',
    action: '状态变更',
    oldValue: 'in_progress',
    newValue: 'completed',
    operatorId: 'user-101',
    operatorName: '张伟',
    createdAt: '2026-05-19T14:20:00',
  },
];

// 周报列表
// 多级审核流程说明：
// 1. 组员提交 → 组长审核 → 管理员终审
// 2. 组长提交 → 管理员直接审核
// 3. 管理员可随时给任何人的周报提修改意见（覆盖组长审核）
export const reportList = [
  // 组长李明的周报 - 管理员直接审核通过
  {
    id: 'report-001',
    authorId: 'user-002',
    authorName: '李明',
    weekNumber: 21,
    year: 2026,
    periodStart: '2026-05-18',
    periodEnd: '2026-05-24',
    content: {
      summary: '本周完成了策略终端量化模块的架构设计，组织组内技术分享会一次。',
      plan: '下周开始推进专业终端组的接口联调工作。',
      issues: '量化回测数据量较大，需要优化存储方案。',
    },
    relatedTaskIds: ['task-001'],
    status: 'reviewed',
    submittedAt: '2026-05-24T16:30:00',
    leaderReviewed: false,
    reviewedBy: 'user-001',
    reviewedByName: '张经理',
    reviewComments: '架构设计考虑周全，继续保持！',
  },
  // 组员张伟的周报 - 已组长审核通过
  {
    id: 'report-002',
    authorId: 'user-101',
    authorName: '张伟',
    weekNumber: 21,
    year: 2026,
    periodStart: '2026-05-18',
    periodEnd: '2026-05-24',
    content: {
      summary: '本周完成了量化策略回测模块的核心功能开发，已通过单元测试。',
      plan: '下周进行性能优化和集成测试。',
    },
    relatedTaskIds: ['task-001'],
    status: 'submitted',
    submittedAt: '2026-05-24T17:00:00',
    leaderReviewed: true,
    leaderReviewedBy: 'user-002',
    leaderReviewedByName: '李明',
    leaderReviewedAt: '2026-05-25T09:00:00',
    leaderReviewComments: '代码质量较高，建议补充性能测试数据。',
  },
  // 组长杨超的周报 - 待管理员审核
  {
    id: 'report-003',
    authorId: 'user-501',
    authorName: '杨超',
    weekNumber: 21,
    year: 2026,
    periodStart: '2026-05-18',
    periodEnd: '2026-05-24',
    content: {
      summary: '本周完成了财富APP新功能的前端开发，正在进行联调测试。',
      plan: '下周完成Bug修复并准备上线。',
    },
    relatedTaskIds: ['task-005'],
    status: 'submitted',
    submittedAt: '2026-05-23T15:00:00',
    leaderReviewed: false,
  },
  // 组员林峰的周报 - 草稿
  {
    id: 'report-004',
    authorId: 'user-801',
    authorName: '林峰',
    weekNumber: 21,
    year: 2026,
    periodStart: '2026-05-18',
    periodEnd: '2026-05-24',
    content: {
      summary: '本周完成了AI客服模型的初步训练，准确率达到了85%。',
      plan: '下周继续优化模型，目标准确率90%。',
    },
    relatedTaskIds: ['task-006'],
    status: 'draft',
    leaderReviewed: false,
  },
  // 组员高翔的周报 - 需修改
  {
    id: 'report-005',
    authorId: 'user-1101',
    authorName: '高翔',
    weekNumber: 20,
    year: 2026,
    periodStart: '2026-05-11',
    periodEnd: '2026-05-17',
    content: {
      summary: '上周进行了交易系统性能优化，但测试中发现部分场景仍有问题。',
      plan: '继续排查性能瓶颈，补充压力测试。',
    },
    relatedTaskIds: ['task-007'],
    status: 'needs_revision',
    submittedAt: '2026-05-18T10:00:00',
    leaderReviewed: true,
    leaderReviewedBy: 'user-012',
    leaderReviewedByName: '黄磊',
    leaderReviewedAt: '2026-05-18T14:00:00',
    leaderReviewComments: '方案可行，需要补充测试报告。',
    reviewedBy: 'user-001',
    reviewedByName: '张经理',
    reviewComments: '测试结果不够充分，请补充高并发场景数据。',
  },
  // 组员吴倩的周报 - 待组长审核
  {
    id: 'report-006',
    authorId: 'user-303',
    authorName: '吴倩',
    weekNumber: 21,
    year: 2026,
    periodStart: '2026-05-18',
    periodEnd: '2026-05-24',
    content: {
      summary: '本周完成了综运数字平台看板的需求分析和原型设计。',
      plan: '下周开始前端页面开发。',
    },
    relatedTaskIds: ['task-004'],
    status: 'submitted',
    submittedAt: '2026-05-24T11:00:00',
    leaderReviewed: false,
  },
  // 组长马腾的周报 - 已审核
  {
    id: 'report-007',
    authorId: 'user-017',
    authorName: '马腾',
    weekNumber: 21,
    year: 2026,
    periodStart: '2026-05-18',
    periodEnd: '2026-05-24',
    content: {
      summary: '本周协调各运维小组完成服务器扩容项目，系统稳定性提升显著。',
      plan: '下周启动自动化测试平台项目。',
    },
    relatedTaskIds: ['task-010'],
    status: 'reviewed',
    submittedAt: '2026-05-24T14:00:00',
    leaderReviewed: false,
    reviewedBy: 'user-001',
    reviewedByName: '张经理',
    reviewComments: '项目管理有方，继续保持！',
  },
];

// 提醒设置
// 周报提醒流程：
// 1. 周五 13:30 - 首次提醒所有人交周报
// 2. 周日 13:30 - 检查提交情况，给未完成员工二次提醒
// 3. 周日 19:00 - 截止并统计结果
export const reminderSettings = {
  // 周报截止设置：周日 19:00
  weeklyReportDeadline: {
    dayOfWeek: 0, // 周日
    hour: 19,
    minute: 0,
  },
  // 首次提醒：周五 13:30（截止前约53.5小时）
  preDeadlineReminder: {
    enabled: true,
    hoursBefore: 53, // 周五13:30到周日19:00约53.5小时
    minute: 30,
    dayOfWeek: 5, // 周五
  },
  // 二次提醒：周日 13:30（截止前5.5小时）
  secondReminder: {
    enabled: true,
    dayOfWeek: 0, // 周日
    hour: 13,
    minute: 30,
    target: 'unsubmitted_only' as const, // 仅提醒未提交人员
  },
  // 逾期提醒（截止后）
  postDeadlineReminder: {
    enabled: true,
    hoursAfter: 1,
    repeatDaily: false, // 周报不需要每日重复
  },
  // 任务到期提醒
  taskDueReminder: {
    enabled: true,
    daysBefore: 1,
  },
  // 任务逾期提醒
  taskOverdueReminder: {
    enabled: true,
    repeatDaily: true,
  },
};

// 仪表盘统计数据
export const dashboardStats = {
  weeklySubmissionRate: 75, // 6份已提交 / 8名成员（不含组长和admin）
  submittedCount: 6,
  totalMemberCount: 8,
  overdueTaskCount: 2,
  pendingReviewCount: 4,
  weeklyActivityData: [
    { week: '第18周', submissions: 12 },
    { week: '第19周', submissions: 14 },
    { week: '第20周', submissions: 10 },
    { week: '第21周', submissions: 6 },
  ],
  // 分组统计数据（管理端视图）
  groupStats: groupList.map((group) => {
    const members = teamMembers.filter((m) => m.groupId === group.id);
    const reports = reportList.filter((r) => members.some((m) => m.id === r.authorId));
    const groupTasks = taskList.filter((t) => members.some((m) => m.name === t.assigneeName));
    return {
      groupId: group.id,
      groupName: group.name,
      leaderName: group.leaderName,
      department: group.department,
      memberCount: members.length,
      taskCompletionRate: groupTasks.length > 0
        ? Math.round((groupTasks.filter((t) => t.status === 'completed').length / groupTasks.length) * 100)
        : 0,
      weeklySubmissionRate: reports.length > 0
        ? Math.round((reports.filter((r) => r.status !== 'draft').length / reports.length) * 100)
        : 0,
      overdueTaskCount: groupTasks.filter((t) => t.status === 'overdue').length,
      pendingReportCount: reports.filter((r) => r.status === 'submitted' && !r.leaderReviewed).length,
    };
  }),
};
